insert into address (cafe_id, city, street, number) values (1, 'Panyambungan', 'Kinsman', '74');
insert into address (cafe_id, city, street, number) values (2, 'Punta Gorda', 'Packers', '05');
insert into address (cafe_id, city, street, number) values (3, 'Līgatne', 'Ridgeview', '16');
insert into address (cafe_id, city, street, number) values (4, 'Dobrljin', 'Mcbride', '83518');
insert into address (cafe_id, city, street, number) values (5, 'Guimarei', 'Shoshone', '69256');
insert into address (cafe_id, city, street, number) values (6, 'Tarariras', 'Butternut', '5306');
insert into address (cafe_id, city, street, number) values (7, 'Qiryat Yam', 'Brickson Park', '79948');
insert into address (cafe_id, city, street, number) values (8, 'Tapada das Mercês', 'Kenwood', '7830');
insert into address (cafe_id, city, street, number) values (9, 'Pilar', 'Stuart', '06');
insert into address (cafe_id, city, street, number) values (10, 'Tabalosos', 'Kedzie', '52');
insert into address (cafe_id, city, street, number) values (11, 'Dehang', 'Hollow Ridge', '06196');
insert into address (cafe_id, city, street, number) values (12, 'Hřebeč', 'Northridge', '58772');
insert into address (cafe_id, city, street, number) values (13, 'Mbandjok', 'Bashford', '9');
insert into address (cafe_id, city, street, number) values (14, 'Asia', 'Dakota', '8');
insert into address (cafe_id, city, street, number) values (15, 'Pawłosiów', 'Huxley', '65712');
insert into address (cafe_id, city, street, number) values (16, 'Tegalbuleud', 'Clarendon', '58537');
insert into address (cafe_id, city, street, number) values (17, 'Dolice', 'Dunning', '15');
insert into address (cafe_id, city, street, number) values (18, 'Kajan', 'Nevada', '1');
insert into address (cafe_id, city, street, number) values (19, 'Rodatychi', 'Mendota', '5270');
insert into address (cafe_id, city, street, number) values (20, 'Jargalant', 'Mosinee', '0804');
insert into address (cafe_id, city, street, number) values (21, 'Cukanguncal', 'Golf', '333');
insert into address (cafe_id, city, street, number) values (22, 'Canillo', 'Towne', '76874');
insert into address (cafe_id, city, street, number) values (23, 'Nishor', 'Waubesa', '6961');
insert into address (cafe_id, city, street, number) values (24, 'Rockford', 'Delaware', '4');
insert into address (cafe_id, city, street, number) values (25, 'Nakatsu', 'Rieder', '36562');
insert into address (cafe_id, city, street, number) values (26, 'Bulls', 'Nova', '7026');
insert into address (cafe_id, city, street, number) values (27, 'Obesi', 'Laurel', '25');
insert into address (cafe_id, city, street, number) values (28, 'As Sayyānī', 'Randy', '2853');
insert into address (cafe_id, city, street, number) values (29, 'Wangcheng', 'Barnett', '76401');
insert into address (cafe_id, city, street, number) values (30, 'Bairro dos Marinheiros', 'Eastlawn', '447');
insert into address (cafe_id, city, street, number) values (31, 'Atyrá', 'Killdeer', '74');
insert into address (cafe_id, city, street, number) values (32, 'Stará Ves nad Ondřejnicí', 'Westridge', '9756');
insert into address (cafe_id, city, street, number) values (33, 'Yuhuazhai', 'Nova', '36');
insert into address (cafe_id, city, street, number) values (34, 'Arevik', '7th', '45');
insert into address (cafe_id, city, street, number) values (35, 'Vale de Santarém', 'Kim', '74');
insert into address (cafe_id, city, street, number) values (36, 'Birmingham', 'Farragut', '7613');
insert into address (cafe_id, city, street, number) values (37, 'Shtip', 'Corben', '18');
insert into address (cafe_id, city, street, number) values (38, 'Sharïngol', 'Shoshone', '20450');
insert into address (cafe_id, city, street, number) values (39, 'Dengzishan', 'North', '27');
insert into address (cafe_id, city, street, number) values (40, 'La Salud', 'Toban', '96');
insert into address (cafe_id, city, street, number) values (41, 'Xinli', 'Alpine', '7');
insert into address (cafe_id, city, street, number) values (42, 'Kotri', 'Cascade', '316');
insert into address (cafe_id, city, street, number) values (43, 'Wenfeng Zhen', 'Sunnyside', '94396');
insert into address (cafe_id, city, street, number) values (44, 'Longtang', 'Mockingbird', '9');
insert into address (cafe_id, city, street, number) values (45, 'Thành Phố Lạng Sơn', 'Algoma', '69932');
insert into address (cafe_id, city, street, number) values (46, 'Sukagawa', 'Fallview', '2319');
insert into address (cafe_id, city, street, number) values (47, 'Goiás', 'Sherman', '899');
insert into address (cafe_id, city, street, number) values (48, 'Bantengan', 'Muir', '5308');
insert into address (cafe_id, city, street, number) values (49, 'Maying', 'Rockefeller', '2635');
insert into address (cafe_id, city, street, number) values (50, 'Denver', 'Shelley', '3');
insert into address (cafe_id, city, street, number) values (51, 'Ussel', 'Oxford', '0');
insert into address (cafe_id, city, street, number) values (52, 'Xianhe', 'Hallows', '94');
insert into address (cafe_id, city, street, number) values (53, 'Stockholm', 'Basil', '28805');
insert into address (cafe_id, city, street, number) values (54, 'Ziyuan', 'Golden Leaf', '2');
insert into address (cafe_id, city, street, number) values (55, 'Pitogo', 'Claremont', '5971');
insert into address (cafe_id, city, street, number) values (56, 'Tangtuzhui', 'Helena', '426');
insert into address (cafe_id, city, street, number) values (57, 'Konggar', 'Schurz', '92');
insert into address (cafe_id, city, street, number) values (58, 'Zel’va', 'American Ash', '043');
insert into address (cafe_id, city, street, number) values (59, 'Taohuajiang', 'Hanson', '4');
insert into address (cafe_id, city, street, number) values (60, 'Mtsamdou', 'Algoma', '19523');
insert into address (cafe_id, city, street, number) values (61, 'Tieling', 'Fuller', '846');
insert into address (cafe_id, city, street, number) values (62, 'Qiaotou', 'Southridge', '4');
insert into address (cafe_id, city, street, number) values (63, 'Longshan', 'Granby', '88');
insert into address (cafe_id, city, street, number) values (64, 'Tanjay', 'Havey', '353');
insert into address (cafe_id, city, street, number) values (65, 'Bent Jbaïl', 'Acker', '9228');
insert into address (cafe_id, city, street, number) values (66, 'Três Pontas', 'Muir', '155');
insert into address (cafe_id, city, street, number) values (67, 'Limoges', 'Anhalt', '253');
insert into address (cafe_id, city, street, number) values (68, 'Greenville', 'Hanover', '80892');
insert into address (cafe_id, city, street, number) values (69, 'Xinzhou', 'Ridgeway', '5543');
insert into address (cafe_id, city, street, number) values (70, 'Santa Lucía', 'Schiller', '649');
insert into address (cafe_id, city, street, number) values (71, 'Nilópolis', 'Dorton', '5');
insert into address (cafe_id, city, street, number) values (72, 'Psáry', 'Esch', '96173');
insert into address (cafe_id, city, street, number) values (73, 'Dunhua', 'Meadow Vale', '426');
insert into address (cafe_id, city, street, number) values (74, 'Briteiros Santa Leocádia', 'Stone Corner', '6');
insert into address (cafe_id, city, street, number) values (75, 'Pordapor Barat', 'Nova', '06');
insert into address (cafe_id, city, street, number) values (76, 'Alukama', 'Susan', '4400');
insert into address (cafe_id, city, street, number) values (77, 'Smederevska Palanka', 'Melrose', '7');
insert into address (cafe_id, city, street, number) values (78, 'Tarlac City', 'Twin Pines', '68');
insert into address (cafe_id, city, street, number) values (79, 'São Domingos', '7th', '98');
insert into address (cafe_id, city, street, number) values (80, 'Heshang', 'Petterle', '23');
insert into address (cafe_id, city, street, number) values (81, 'Stockholm', 'Kropf', '6684');
insert into address (cafe_id, city, street, number) values (82, 'Communal', 'New Castle', '9684');
insert into address (cafe_id, city, street, number) values (83, 'Cap-Santé', 'Prairie Rose', '57515');
insert into address (cafe_id, city, street, number) values (84, 'Ipu', 'Menomonie', '885');
insert into address (cafe_id, city, street, number) values (85, 'Kalahang', 'Monterey', '1271');
insert into address (cafe_id, city, street, number) values (86, 'Kamieniec Podolski', 'Butternut', '945');
insert into address (cafe_id, city, street, number) values (87, 'Balauring', 'Anderson', '8');
insert into address (cafe_id, city, street, number) values (88, 'Oyo', 'Morningstar', '48');
insert into address (cafe_id, city, street, number) values (89, 'Bulri', 'Forster', '773');
insert into address (cafe_id, city, street, number) values (90, 'Guanbuqiao', 'Blackbird', '3');
insert into address (cafe_id, city, street, number) values (91, 'Zhudian', 'Prairieview', '338');
insert into address (cafe_id, city, street, number) values (92, 'Ilām', 'Little Fleur', '2076');
insert into address (cafe_id, city, street, number) values (93, 'Blagoveshchensk', 'Gulseth', '01');
insert into address (cafe_id, city, street, number) values (94, 'San Agustín de Valle Fértil', 'Morningstar', '5');
insert into address (cafe_id, city, street, number) values (95, 'Dar Chabanne', 'Tennyson', '1');
insert into address (cafe_id, city, street, number) values (96, 'Vincennes', 'Raven', '004');
insert into address (cafe_id, city, street, number) values (97, 'Växjö', 'Dovetail', '8184');
insert into address (cafe_id, city, street, number) values (98, 'Inawashiro', 'Dwight', '86');
insert into address (cafe_id, city, street, number) values (99, 'Kulaman', 'Paget', '3493');
insert into address (cafe_id, city, street, number) values (100, 'Bërxull', 'Granby', '84508');
